version: "3.9"

services:
  app:
    image: voice-game
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APPLICATION_PORT:-3000}:${APPLICATION_PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped
